
"use client";

import { useRouter } from "next/navigation";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

export default function DisclaimerPage() {
  const router = useRouter();

  return (
    <main className="flex min-h-screen flex-col items-center bg-background p-4 sm:p-6 lg:p-8">
      <div className="w-full max-w-2xl space-y-6">
        <header className="relative flex items-center justify-center">
          <Button variant="ghost" size="icon" className="absolute left-0" onClick={() => router.push('/')}>
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <h1 className="font-headline text-2xl font-bold">Disclaimer</h1>
        </header>
        
        <Card className="shadow-lg">
            <CardHeader>
                <CardTitle>Important Information</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 text-muted-foreground">
                <p>
                    This is a Web-based Reward Application. Users can earn points only by completing in-app tasks which require them to watch an AdMob advertisement.
                </p>
                <p>
                    No advertisements will be shown anywhere else inside the app outside of these tasks.
                </p>
                <p>
                    Once the user reaches the minimum threshold of ₹500, they can withdraw their earnings via UPI/Bank transfer.
                </p>
                <p>
                    All rewards and withdrawals are funded ONLY from the Google AdMob advertising revenue generated by these task-based ads.
                </p>
                <p>
                    There is no gambling, betting, or lottery involved. The app is purely for entertainment and reward purposes, and it complies fully with Google Play policies.
                </p>
            </CardContent>
        </Card>

      </div>
    </main>
  );
}
