
"use client";

import { useRouter } from "next/navigation";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

export default function DisclaimerPage() {
  const router = useRouter();

  return (
    <main className="flex min-h-screen flex-col items-center bg-background p-4 sm:p-6 lg:p-8">
      <div className="w-full max-w-2xl space-y-6">
        <header className="relative flex items-center justify-center">
          <Button variant="ghost" size="icon" className="absolute left-0" onClick={() => router.push('/')}>
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <h1 className="font-headline text-2xl font-bold">Disclaimer</h1>
        </header>
        
        <Card className="shadow-lg">
            <CardHeader>
                <CardTitle>Important Information</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 text-muted-foreground">
                <p>
                    This is a Web-based Reward Application where each user task includes multiple AdMob ad formats such as Poster Ads, Banner Ads, and Rewarded Video Ads.
                </p>
                <p>
                    Users are required to view these ads as part of completing the task. After completing one task, a new task automatically becomes available, allowing users to engage with ads anytime without daily limits.
                </p>
                <p>
                    Rewards are granted only after the user completes the full task (which includes watching all ad formats).
                </p>
                <p>
                    Once the user reaches the minimum threshold of ₹500, they can withdraw their earnings via UPI/Bank transfer.
                </p>
                <p>
                    All rewards and withdrawals are funded ONLY from the Google AdMob advertising revenue generated by these task-based ads.
                </p>
                <p>
                    There is no gambling, betting, or lottery mechanism included. The app is purely for entertainment and reward purposes and complies fully with Google Play policies.
                </p>
            </CardContent>
        </Card>

      </div>
    </main>
  );
}
